CREATE DATABASE IF NOT EXISTS login;

USE login;

CREATE TABLE IF NOT EXISTS usuario(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(140) NOT NULL,
    SENHA VARCHAR(16) NOT NULL
);
